### ISSUE TITLE
json error

### ISSUE THREAD

**Issue by galzil** [nitaybz/homebridge-switcher-boiler#1]
HOOBS 3.2.6
My json
`{
    "accessory": "SwitcherBoiler",
    "name": "Boiler",
    "debug": true
}`
this is the error
`[Boiler] SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>:null:null)
    at Socket.<anonymous> (/home/hoobs/.hoobs/node_modules/homebridge-switcher-boiler/lib/api.js:20:27)
    at Socket.emit (events.js:322:22)
    at Pipe.<anonymous> (net.js:672:12)`

Thanks for the plugin

**Comment by kupy25** [comment]
11.6.2020, 22:42:00 [Boiler] Discovering Switcher Device...
11.6.2020, 22:42:00 [Boiler] Could NOT discover devices!! -> Checking in storage for cached config...
11.6.2020, 22:42:00 [Boiler] Traceback (most recent call last):
  File "/home/hoobs/.hoobs/node_modules/homebridge-switcher-boiler/lib/switcher.py", line 116, in <module>
    print("{ \"status\": \"success\", \"deviceID\": \"" + device_id + "\", \"deviceIP\": \"" + switcherIP + "\" }")
TypeError: can only concatenate str (not "bytes") to str
11.6.2020, 22:42:00 (node:731) UnhandledPromiseRejectionWarning: Error: NOT DISCOVERED & NOT CACHED
11.6.2020, 22:42:00 at /home/hoobs/.hoobs/node_modules/homebridge-switcher-boiler/index.js:103:13
11.6.2020, 22:42:00 at processTicksAndRejections (internal/process/task_queues.js:97:5)
11.6.2020, 22:42:00 (node:731) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
11.6.2020, 22:42:00 (node:731) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
11.6.2020, 22:42:00 [Boiler] 
11.6.2020, 22:42:00 [Boiler] SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at Socket.<anonymous> (/home/hoobs/.hoobs/node_modules/homebridge-switcher-boiler/lib/api.js:20:27)
    at Socket.emit (events.js:322:22)
    at Pipe.<anonymous> (net.js:672:12)
11.6.2020, 22:49:59 [Boiler] Getting Switcher State (interval)
11.6.2020, 22:50:03 [Boiler] { "status": "failed", "message": "[Errno -2] Name or service not known" }
11.6.2020, 22:50:03 [Boiler] ERROR Getting State from the Switcher:
11.6.2020, 22:50:03 [Boiler] Error: [Errno -2] Name or service not known

**Comment by nitaybz** [comment]
Ok those are 2 different issues...
Regarding the first, I'll try to correct this JSON.parse error to give me better view on the error. Is there a chance there is already more logs you've not shared that might be relevant?

Also, if both of you can please share your device information? What device? What is the firmware version?

Thanks

**Comment by galzil** [comment]
I have a V2 with firmware 3.21
More from the log:
`[Boiler] { "status": "failed", "message": "[Errno -2] Name or service not known" }
12.6.2020, 14:25:11 [Boiler] ERROR Getting State from the Switcher:
12.6.2020, 14:25:11 [Boiler] Error: [Errno -2] Name or service not known
12.6.2020, 14:25:13 [People] Changed occupancy state for h-iPhone-sl-wr to true. Last successful ping 2020-06-12T05:25:13-06:00 , last webhook none .
12.6.2020, 14:25:14 [Boiler] { "status": "failed", "message": "[Errno -3] Temporary failure in name resolution" }
12.6.2020, 14:25:14 [Boiler] ERROR Getting State from the Switcher:
12.6.2020, 14:25:14 [Boiler] Error: [Errno -3] Temporary failure in name resolution`

**Comment by nitaybz** [comment]
all errors should be fixed now with version 1.0.5
please update the plugin (delete the plugin and reinstall if not working) and close the issue if it's resolved

**Comment by galzil** [comment]
Thank you!
