### ISSUE TITLE
Port collesion on 20002 with other plugins?

### ISSUE THREAD

**Issue by erlichmen** [nitaybz/homebridge-switcher-boiler#11]
I'm getting this error when installing v2.0.7 which prevents Homebridge to start.
 
Error: bind EADDRINUSE 0.0.0.0:20002
    at dgram.js:338:20
    at processTicksAndRejections (internal/process/task_queues.js:85:21)

I can't find the port in the code which is wired, but after uninstalling the plugin Homebridge starts again.
This is something new that happens after the upgrade as the previous version worked

**Comment by nitaybz** [comment]
The plugin does not play well yet with multiple devices... I'm working on a platform version.

in the meantime I released v2.0.8 which should solve some issues so it won't throw the errors

**Comment by nitaybz** [comment]
Try the latest version 3

**Comment by erlichmen** [comment]
Works for me! (Boiler and Power plug)
