### ISSUE TITLE
Version 3 configuration on Hoobs

### ISSUE THREAD

**Issue by galzil** [nitaybz/homebridge-switcher-boiler#12]
Please note that the config using web-ui-x on hoobs is incorrect, it tries to add an accessory and not a platform.
I've configured it maually and it works great.

**Comment by nitaybz** [comment]
can it be just cache of the old plugin? have you notice any problems in the config schema?

**Comment by nitaybz** [comment]
what happen now if you remove the plugin and re-add? still uses accessory?

**Comment by galzil** [comment]
I deleted the plugin, restarted the homebridge service and than installed as new. 
When pressing the configuration button it tries to add an accessory. 
Maybe it's a cache issue. Let's see if anybody else has this. 
Anyway, thanks for the amazing work you do here, as mentioned the plugin works when configured manually

**Comment by nitaybz** [comment]
I did get another similar feedback from a user... but I think it was a cache issue because it was resolved after another deletion and reboot
