### ISSUE TITLE
Switch turns itself back off specifically via Home app

### ISSUE THREAD

**Issue by freak4pc** [nitaybz/homebridge-switcher-boiler#13]
Hey Nitay, great plugin :) Thank you for the great work.

The plugin detected both my Switcher devices (AC Plug and Boiler Switcher)

AC Plug seems to work great (on/off).
For the boiler - turning on and waiting 5-6 seconds automatically gets turned off. 

See video:

![RPReplay_Final1604153726](https://user-images.githubusercontent.com/605076/97781492-7cedc880-1b94-11eb-82a4-5b1e39932b2d.gif)

Debug logs don't seem to have any info about this (even with Debug mode on in the plugin settings):

```
[10/31/2020, 4:15:09 PM] [Switcher Boiler] Turning ON Switcher Boiler 8DBE 
[10/31/2020, 4:15:14 PM] [Switcher Boiler] Turning ON Switcher Boiler 8DBE 
```

Appreciate your help! 
Shai

**Comment by nitaybz** [comment]
Seems like it's not turning on and just goes back to current state.... what's your switcher firmware version?

**Comment by freak4pc** [comment]
65.07

**Comment by nitaybz** [comment]
It's outdated and probably the reason you can't control it... try upgrading the firmware, restart homebridge and let me know

**Comment by freak4pc** [comment]
Thanks. Seems like it is the latest based on the app, at least. Am I missing something? 
![IMG_9D883B55890F-1](https://user-images.githubusercontent.com/605076/97788331-d9ff7380-1bc0-11eb-921b-4d6317228128.jpeg)

**Comment by nitaybz** [comment]
What switcher version is it?
There must be a way to upgrade it...
It should be at least version 72.32

**Comment by freak4pc** [comment]
v2... strange. I'll keep digging into this, not sure why it's not showing me an update /:

**Comment by freak4pc** [comment]
Yup, firmware version was the issue. Thank you! :)

**Comment by nitaybz** [comment]
no problem... glad I could help
