### ISSUE TITLE
The requested accessory "switcherBoiler" was not registered by any plugin

### ISSUE THREAD

**Issue by idanyc** [nitaybz/homebridge-switcher-boiler#2]
Running Hoobs 3.2.6 (node version 12.16.2) on Pii Zero
Switcher V2

logs:
6/11/2020, 11:48:00 PM The requested accessory "switcherBoiler" was not registered by any plugin.
6/11/2020, 11:48:00 PM Your config.json is requesting the accessory "switcherBoiler" which has not been published by any installed plugins.

config:
    {
        "accessory": "switcherBoiler",
        "plugin_map": {
            "plugin_name": "homebridge-switcher-boiler",
            "index": 0
        },
        "pollingIntervalInSec": 30,
        "name": "Boiler",
        "debug": true
    }

**Comment by idanyc** [comment]
{
            "accessory": "switcherBoiler",
            "plugin_map": {
                "plugin_name": "homebridge-switcher-boiler",
                "index": 0
            },
            "pollingIntervalInSec": 30,
            "name": "Boiler",
            "debug": true
        }

**Comment by nitaybz** [comment]
Looks like the plugin is not installed. Can you share some logs?

**Comment by idanyc** [comment]
6/12/2020, 12:10:45 AM + homebridge-switcher-boiler@1.0.1
added 2 packages from 3 contributors in 52.374s
6/12/2020, 12:10:50 AM 
35 packages are looking for funding
  run `npm fund` for details
6/12/2020, 12:10:50 AM Plugin "homebridge-switcher-boiler" installed.
6/12/2020, 12:10:50 AM Got SIGINT, shutting down Bridge...
6/12/2020, 12:11:12 AM Loaded plugin "homebridge-switcher-boiler".

6/12/2020, 12:12:26 AM Loaded plugin "homebridge-switcher-boiler".
6/12/2020, 12:12:30 AM The requested accessory "switcherBoiler" was not registered by any plugin.
6/12/2020, 12:12:30 AM Your config.json is requesting the accessory "switcherBoiler" which has not been published by any installed plugins.

are there any additional logs? where can i find them?

**Comment by nitaybz** [comment]
Uploaded a fix. please update to 1.0.2

**Comment by nitaybz** [comment]
all errors should be fixed now with version 1.0.5
please update the plugin (delete the plugin and reinstall if not working) and close the issue if it's resolved

**Comment by idanyc** [comment]
Solved in 1.0.4
Many Thanks!
