### ISSUE TITLE
Error: Operation failed, Could not acquire SessionID, Please try again

### ISSUE THREAD

**Issue by matanz121** [nitaybz/homebridge-switcher-boiler#3]
when trying to turn on/turn off the switcher, I get the below message -
Error: Operation failed, Could not acquire SessionID, Please try again

If I'm turning on the switcher locally - I can see that the state changes in the homebridge UI.
But I don't have the option to change it by myself from the GUI.

**Comment by nitaybz** [comment]
Please make sure your machine (running homebridge) date and time are accurate and set correctly

**Comment by matanz121** [comment]
Hi,
looks like everything set correctly.
timezone + date - correct.

anything else?

**Comment by nitaybz** [comment]
usually the sessionID error occurring when there is time difference between the switcher and the homebridge machine..
It can also happen when you try to execute few requests close to each other...

does it happen all the time or every now and then?

**Comment by matanz121** [comment]
pi@raspberrypi:/usr/local/lib/node_modules/homebridge/lib $ date
Tue  7 Jul 20:08:58 IDT 2020

the local time in Israel is also - 20:08.
also, I see in the switcher app that the time is the same.

it happens all the time. I tried to reboot the home bridge but doesn't change anything.

**Comment by nitaybz** [comment]
What version is your switcher? What firmware? On what machine are you running homebridge?
What version of python do you use?

**Comment by matanz121** [comment]
Switcher version - 2.29 (IOS)
FIRMWARE - 71.00 Switcher Boiler 3DC4 - look like I have an update - but I do not know why I can't update
I'm running homebride on rasberian os on rasberrypy zero w
 Python version 2.7.16 installed when I'm running python --version in the os

**Comment by matanz121** [comment]
now I updated the firmware to - 72.36
still the same error - 
[7/7/2020, 21:51:01] [Boiler] ERROR Turning ON the Switcher
[7/7/2020, 21:51:01] [Boiler] Error: Operation failed, Could not acquire SessionID, Please try again...
[7/7/2020, 21:51:01] [Boiler] NOT TRYING AGAIN!!

When I'm turning on the boiler from the switcher app I can see that the homebridge retrieves the info. 
the get function works perfect. 
the rest not working.

**Comment by nitaybz** [comment]
Did you try to restart homebridge after the firmware update?

**Comment by nitaybz** [comment]
anyway with the previous Switcher firmware it shouldn't have worked... but now after a good restart I believe it should work

**Comment by matanz121** [comment]
yes, now it starts work from Homekit. I can tell Siri to turn on & off the boiler. 
from the HomeBridge UI, it doesn't work well, but it's enough for me.

thanks for your support!
BTW, is there any option to turn on the boiler for 30min for example? or just turn on/off?

**Comment by nitaybz** [comment]
if you set the accessory type to valve you can set default duration for the switcher from Home app, but the minimum is 1 hour as it is bound to the "Auto Shutdown" feature in Switcher app.
although if you don't set the accessory type to valve you can still set the duration from Eve app.
