### ISSUE TITLE
Plugin stopped working

### ISSUE THREAD

**Issue by galzil** [nitaybz/homebridge-switcher-boiler#6]
HOOBS 3.2.6
Switcher V2 with firmware 3.32
My json
```
{
    "accessory": "SwitcherBoiler",
    "accessoryType": "valve",
    "name": "Boiler",
    "pollingIntervalInSec": 60,
    "debug": false
}
```

I get this error since the last update:
```
[Boiler] ERROR Getting State from the Switcher:
[Boiler] Error: [Errno 113] No route to host
```

**Comment by galzil** [comment]
more info:
the switcher is detected on load:
`[Boiler]  ~~~~~~ DISCOVERED SWITCHER DEVICE (192.168.xxx.xxx) ~~~~~~`
but than this happens:
`(node:11847) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 shutdown listeners added to [API]. Use emitter.setMaxListeners() to increase limit
[Boiler] ERROR Getting State from the Switcher (interval):
[Boiler] Error: [Errno -2] Name or service not known`
and the error goes on loop

**Comment by nitaybz** [comment]
check version 2.0
