### ISSUE TITLE
New version not working on HOOBS

### ISSUE THREAD

**Issue by galzil** [nitaybz/homebridge-switcher-boiler#9]
I've just upgraded to 2.0.1
The plugin is not loading on on HOOBS
`The requested accessory "SwitcherBoiler" was not registered by any plugin.
Your config.json is requesting the accessory "SwitcherBoiler" which has not been published by any installed plugins.`

**Comment by galzil** [comment]
This is a HOOBS issue,
I've updated the line:
`api.registerAccessory('SwitcherBoiler', SwitcherBoiler)`
to:
`api.registerAccessory('homebridge-switcher-boiler', 'SwitcherBoiler', SwitcherBoiler)`
in index.js and now it's loading and working

**Comment by nitaybz** [comment]
Thanks... I updated the code
